### ISSUE TITLE
Android App does not login on Android 30

### ISSUE THREAD

**Issue by sachindrakumar** [PatilShreyas/NotyKT#301] opened 2021-11-02 06:44 UTC
The android APP is working fine when Emulator is Android 26 but fails to even login when run on Android 30.
Am running both API and Android App locally on machine.

**Comment by PatilShreyas** [comment] 2021-11-03 09:38
@sachindrakumar Can you provide any log which can help in debugging?

**Comment by sachindrakumar** [comment] 2021-11-07 09:10
Hi,
There was no log output of the error, although I recognised that on Android
28+, the plain http requests were blocked and I had to tweak the
NetworkSettings of the app to allow plain text communication.

Sachindra Kumar
Mobile: +91 98970 68084
e-mail: ***@***.***
Yahoo: ***@***.***
Skype: ***@***.***
--------------------------------------------------------------------------------------
Save a tree...Please don't print this e-mail unless you really need to.

**Comment by PatilShreyas** [comment] 2022-10-05 14:31
Since this is not actually an issue, closing this. Feel free to re-open the issue if the problem is reproducible.

**Closed by PatilShreyas** 2022-10-05 14:31 UTC
