### ISSUE TITLE
Can't add more than 1 note

### ISSUE THREAD

**Issue by IAMISSAM** [PatilShreyas/NotyKT#174] opened 2021-06-14 10:49 UTC
Hello, when i add a note, i'm redirected to the main notes fragment, and when i click on the Add FAB, the app navigate to the AddNoteFragment and instantly navigate back to the NotesFragment, because in the AddNoteViewModel, the viewState variable is not reset when a new note is created and if we navigate in AddNoteFragment it will re-observe the Success state of the viewState and navigate back

**Comment by PatilShreyas** [comment] 2021-07-06 15:11
@IAMISSAM can you attach a video?

**Comment by PatilShreyas** [comment] 2021-08-06 12:22
Closing issue since not having a proper issue description. Feel free to re-open whenever you are able to successfully reproduce the same issue. Thanks!

**Closed by PatilShreyas** 2021-08-06 12:22 UTC
